on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: Notepad pipeline
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run pipeline
        uses: ./ # Uses an action in the root directory
        id: pipeline

